### PR TITLE
perf: remove unused css/icons.styl: ic-public

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
This was never ever used.
### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by jungeun-cho** [comment]
The work of using private and public icons needs improvement.
You should consider both the default and detailed popups.

**Comment by dilyanpalauzov** [comment]
ic-lock.png is used in `tui-calendar-popup-detail tui-calendar-schedule-private` and in `tui-calendar-icon.tui-calendar-ic-private`.

ic-unlock.png is used in `tui-calendar-icon.tui-calendar-ic-public` and in `tui-calendar-section-private.tui-calendar-public .tui-calendar-ic-private`.

While `ic-lock` is used only for classes containing `private`, ic-unlock is used for classes containing both the `ic-private` and `ic-public` in their names.

This is confusing.

**Comment by dilyanpalauzov** [comment]
Which is the template for the default popup and which is the template for the detailed popup?

**Comment by jungeun-cho** [comment]
ok to test

**Comment by jungeun-cho** [comment]
I confirmed that it is used with `.section-private`.
Hm... 
```css
.tui-full-calendar-section-private.tui-full-calendar-public .tui-full-calendar-ic-private
```

But, We need to change the `.tui-full-calendar-ic-private` selector.
I'm confused because it is displaying both public and private.
For example. `ic-private-or-public`...

I will also edit this as I [edit the private schedule related messages.](#626)

**Pull request merged**
