### PR TITLE
fix datetime range

### PR DESCRIPTION
**Pull request by xiongxiaoliang**
Xnip2019-11-14_17-03-53

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by dongsik-yoo** [comment]
How do I reproduce this issue? Please let me know the steps. Thank you.

**Comment by xiongxiaoliang** [comment]
Please use the `schedules` in `demo.js` to reproduce. Thank you. @dongsik-yoo 

[demo.js.zip](https://github.com/nhn/tui.calendar/files/3886441/demo.js.zip)

**Comment by xiongxiaoliang** [comment]
image

**Comment by dongsik-yoo** [comment]
Thank you for your effort and PR. But this data must be TZDate type, not number type. So I could reproduce this issue with your event data and I found a code problem. We will fix this by different solution.

datetime.js
```js
    convertStartDayToLastDay: function(d) {
        var date = new TZDate(d);
        var isStartOfDay = datetime.isStartOfDay(d);

        return isStartOfDay ? date.setDate(date.getDate() - 1) : date;
    },
```

**Comment by xiongxiaoliang** [comment]
Thank you.

**Comment by dongsik-yoo** [comment]
I'll fix this on #471. Close this.

**Pull request closed without merging**
