### PR TITLE
feat: create schedules from url using json (Question: #414)

### PR DESCRIPTION
**Pull request by Djunnni**
this is a feature for creating schedules from json.

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description
~~~
calendar.createSchedulesFromUrl("/example");
~~~
this function gets JSON Array from url and use "createSchedules"

i referred to https://xhr.spec.whatwg.org/#progressevent and https://developer.mozilla.org/ko/docs/Web/API/XMLHttpRequest

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by dongsik-yoo** [comment]
@Djunnni Hi, thank you for your effort and PR. But we need to discuss that TOAST UI Calendar has network API. There are more considerable things to think like react, vue wrapper.

**Comment by Djunnni** [comment]
@dongsik-yoo 
Thanks for commenting. 
I think user can save effort if TOAST UI Calendar has network API. 
ex) Sharing schedules, Getting schedules etc..
After discuss for network API, Could i join?
i want to listen RoadMap and am interested in improve function :)
djunnni@gmail.com
Thanks.

**Comment by dongsik-yoo** [comment]
@Djunnni The network APIs are more complex than this PR. I think CRUD APIs are necessary to be complete. What do you think?

**Comment by Djunnni** [comment]
I think this PR is poor to request commit. But i want to tell needs of Network api.
For CRUD APIs, several rules are necessary. aren't it? 
1.  How to make Design Pattern for RESTful?
2. using jsonp to prevent cross-origin
3. _network is need

how about?

**Pull request closed without merging**
