### PR TITLE
common.getScheduleChanges: rationalize util.isEmpty call

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
This is much easier to understand, than using util.isEmpty(), and is also faster.

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by jungeun-cho** [comment]
ok to test

**Comment by jungeun-cho** [comment]
@dongsik-yoo 
Please give us your thoughts on this PR.

**Comment by dongsik-yoo** [comment]
I think it's a kind of micro tuning. I don't think it' easier to understand. It's just same.

**Comment by dilyanpalauzov** [comment]
`return util.isEmpty(changes) ? null : changes;` exands to
```javascript
        if (typeof changes === 'undefined' || changes === null
            || ((typeof changes === 'string' || changes instanceof String) && changes === '')) {
            return null;
        }

        if (changes instanceof Array || changes.toString() === '[object Arguments]' || !!changes.callee) {
            return changes.length === 0 ? null : changes;
        }

        if (changes === Object(changes) && !(changes instanceof Function)) {
            return changes.keys().length ? changes : null;
        }

        return changes;
```
To get this expansion one has to check the body of many functions and the expansion is cumbersome to read.  Moreover changes is for sure not a function, arguments, or array.

**Comment by jungeun-cho** [comment]
@dilyanpalauzov 
Please respect our issue template form.

**Pull request closed without merging**
