### PR TITLE
docs: fixed import css path

### PR DESCRIPTION
**Pull request by Tragio**
### Please check if the PR fulfills these requirements

- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

Fixed missing `/dist/` on importing CSS file.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by adhrinae** [comment]
@Tragio
Thanks for your contribution. We already exporting CSS files in the package root so that users don't have to think about the `dist` directory.

https://github.com/nhn/tui.calendar/blob/main/apps/calendar/package.json#L18-L19

So I don't think these changes are unnecessary. I was wondering if you couldn't import CSS files without adding `/dist` to your import path.

**Comment by Tragio** [comment]
@adhrinae if I do as it is written in the docs I got:

```
This dependency was not found:                                                                                                                                        
* @toast-ui/calendar/toastui-calendar.min.css in ./node_modules/@nuxt/webpack/node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/organism/Calendar.vue?vue&type=script&lang=js&
```

**Comment by adhrinae** [comment]
@Tragio I didn't get the errors while testing on React/Vue sandboxes.
Perhaps Nuxt's module resolution is causing the problem.

I found that adding a `css` element in the `nuxt.config.js` file could resolve the problem, however, it's not a general solution for someone who wants to lazy-load the calendar component.

```js
// nuxt.config.js
export default {
  // ...
  css: ["@toast-ui/calendar/toastui-calendar.min.css"],
  // ...
}
```

What about adding a small section for using the calendar with Nuxt, instead of replacing the current documentation? like:

```md
### Usage with Nuxt

You need to import the CSS file in a different path.

...
```

**Comment by adhrinae** [comment]
@Tragio
That's brilliant 👍 
Anyway, I think this is a Nuxt-specific problem. or Webpack.
I've only tried importing the CSS file with Vite and Parcel.

So let's close this PR and change it to an issue about this situation. After that, we'll investigate this problem and decide whether we fix it or write a note about it in the documentation.

**Pull request merged**
