### PR TITLE
Simplify common.limit calls: do not pass arrays

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by jungeun-cho** [comment]
ok to test

**Comment by jungeun-cho** [comment]
Could you please modify the TC for `limit`?
and
Please respect the [Commit Message Convention](https://github.com/nhn/tui.calendar/blob/master/docs/COMMIT_MESSAGE_CONVENTION.md).

**Comment by jungeun-cho** [comment]
@dilyanpalauzov 
Please respect our issue template form.

**Pull request closed without merging**
