### PR TITLE
Fix: bug fixes (fix #470, fix #487, fix #488)

### LINKED ISSUE #470: hide resize icon when isReadOnly=true is set for calendar widget
Hi,

When one sets isReadOnly=true for each schedule, the resize icon is hidden. 

However, when isReadOnly=true is set for calendar widget, the resize icon still shows (resizing is disabled though).
```
<calendar
                        ref="calendar"
                        :calendars="calendars"
                        :schedules="schedules"
                        style="height: auto;"
                        :isReadOnly="true"
                    />
```

Please hide resize icon when isReadOnly=true is set for calendar widget. Thanks!

Maybe related: https://github.com/nhn/tui.calendar/commit/ca87dd5bc134a21df01a84e057da4022e0eed8ee

### LINKED ISSUE #487: Passing template option to setOptions does not apply
## Version
v.1.12.9

## Development Environment
Chrome

## Current Behavior

From https://github.com/nhn/toast-ui.react-calendar/issues/21
* When user changes calendar view - onChangeCalendarView even calls

```js
cal.setOptions({
  template: { time: getTimeTemplate(calendarView) }
});
```

* Function getTimeTemplate is like
```js
const getTimeTemplate = (calendarView) => (schedule) => {
  return calendarView === 'month' ? 'aaa' : 'bbb';
};
```
* The template of time is not changed
## Expected Behavior

The template should be changed

### LINKED ISSUE #488: Timezone: wrong offset calculation when offsets are 30 minutes apart (first tz is 30 minutes ahead than second)
Timezones comparison rendering works well except this one case when the first timezone is 30 minutes ahead of the second. Rather than subtracting 30 minutes from the second timezone its adding 30 minutes to it.
Please take a look at [this codepen](https://codepen.io/snyaggarwal/pen/OJPoNEb).
The timezones are rendered wrong (relatively).

Expected behavior - first timezone(+570) should be 30 minutes ahead of the second timezone(+540).

### PR DESCRIPTION
**Pull request by jungeun-cho**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description
* fix: Fixed resize button being displayed in weekly view(timeGrid) when `isReadOnly=true` as Calendar option(fix #470) 
* fix : Fixed the problem which is not applied when changing template, timezones, calendars property value in `setOptions`(fix #487)
* fix : Resolved an issue where the time range was not normally represented in the time grid when the difference between the main time zone offset and the secondary time zone offset was less than 1 hour (fix #488 ) 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by jungeun-cho** [comment]
ok to test

**Comment by dongsik-yoo** [comment]
[01/23] Reviewed. Nothing to comment. Well done!

**Comment by dongsik-yoo** [comment]
I forgot this. The 8876261737e772c208dcc4478a1e37b8d03c80c9 commit log has wrong issue number. It should be #488.

**Comment by jungeun-cho** [comment]
@dongsik-yoo 
Fixed incorrect issue numbers in the commit log.

**Pull request merged**
