### PR TITLE
chore: fix broken test case

### PR DESCRIPTION
**Pull request by jungeun-cho**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description
* resolve: Resolve incorrect coordinates to calculate where new calendar creation popups appear when in weekly working time view mode
스크린샷 2020-02-26 10 13 15

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by dongsik-yoo** [comment]
Why don't you use `snippet.pick()` function to get nullable property `options.workweek`?

**Comment by dongsik-yoo** [comment]
[02/26] reviewed.

**Comment by jungeun-cho** [comment]
ok to test

**Comment by jungeun-cho** [comment]
@dongsik-yoo 
applied your feedback

**Pull request merged**
