### PR TITLE
chore: introduce pre-commit hooks 

### PR DESCRIPTION
**Pull request by adhrinae**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

* This PR enables Git pre-commit hooks using `husky` and `lint-staged`

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Review by lja1018 — APPROVED** [review]
리뷰완료합니다. 고생하셨습니다!

**Review by jajugoguma — APPROVED** [review]
리뷰 완료합니다! 고생하셨습니다!

**Review by dongsik-yoo — COMMENTED** [review]
리뷰 완료합니다. 수고하셨습니다.

커밋 메시지에서 환경 변경 사항의 프리픽스는 `env: `를 쓰기로 했습니다. 참고 부탁드립니다.
작년에 정한 것 같은데, 정리된 자료가 어디 있는지 못찾겠네요.
내일 메신저 방에 한번 물어봅시다.

**Pull request merged**
